```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}

opts_knit$set(base.dir='./', fig.path='', out.format='md')
opts_chunk$set(cache.path='cache/', fig.path='img/', cache=FALSE, tidy=TRUE, fig.keep='high', echo=TRUE, dpi=300, out.width=700, prompt=FALSE, comment='##', results='markup', eval=FALSE)
# See yihui.name/knitr/options for more Knitr options.
```

Custom data
============

Custom features of interest (FOIs)
-----------------------------

Sometimes we may want to have sets of features of interest readily accessible for the analysis, such as demo sets, or sets of random features. We may place the BED files with genomic coordinates of such FOIs in the subfolders under the `[dir]/custom_data/fois/[organism]/` folder. The names of the subfolders serve as descriptions of the sets of FOIs.

An example of the `fois` folder may look like:

```
/home/testuser/Documents/db_1.01_05.12.2014/custom_data/fois/hg19/GWAStest1/*.bed
/home/testuser/Documents/db_1.01_05.12.2014/custom_data/fois/hg19/GWASrand/*.bed
/home/testuser/Documents/db_1.01_05.12.2014/custom_data/fois/hg19/SNPsCommonRand/*.bed
/home/testuser/Documents/db_1.01_05.12.2014/custom_data/fois/hg19/GWAScatalogFull/*.bed
```

Custom genomic features (GFs)
-----------------------

Some genome annotation tracks contain information about different biologically relevant features, combined together. An example of such combined table is the `wgEncodeRegTfbsClusteredV3` track, containing experimentally detected transcription factor binding sites for 161 different transcription factors. We may want to consider the data for each transcription factor separately. We process such combined data using the `extract_UCSC.py` script (see the `db` subfolder in the [source code](https://github.com/mdozmorov/genome_runner) folder). We place extracted BED files in the `[dir]/custom_data/gfs/hg19/tfbsEncode` folder. The `tfbsEncode` GFs will be accessible through GenomeRunner's web interface.

It is a good idea to remove special characters from file names, if any, by running:

```
for FILE in *.bed; do mv -v "$FILE" echo $FILE | tr ' ' '_' | tr -d '[{}(),!]' | tr -d "'" | tr '[A-Z]' '[a-z]' | sed 's/_-_/_/g';done
```

An example of the `gfs` folder may look like:

```
/home/testuser/Documents/db_1.01_05.12.2014/custom_data/gfs/hg19/tfbsEncode/*.bed
/home/testuser/Documents/db_1.01_05.12.2014/custom_data/gfs/hg19/H3K4me3/*.bed
/home/testuser/Documents/db_1.01_05.12.2014/custom_data/gfs/hg19/gwasCatalog/*.bed
/home/testuser/Documents/db_1.01_05.12.2014/custom_data/gfs/hg19/chromStates/*.bed
```

Random sets of SNPs
--------------------
Random SNP sets are used to check for the lack of enrichment. They can be generated from a background file using the following command:
```
for i in {10..19}; do n=$((2**i)); zcat snp128.bed.gz | shuf | head -n $n > rndsnp128_$n.bed; done
```

The logic here is to generate random SNP sets of different sizes. The sizes are determined by power of 2, {10..19} range here, so the first set will contain 2^10=1024 random SNPs, the second - 2^11 etc. Those random SNP sets can be placed into 
