```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}

opts_knit$set(base.dir='./', fig.path='', out.format='md')
opts_chunk$set(cache.path='cache/', fig.path='img/', cache=FALSE, tidy=TRUE, fig.keep='high', echo=TRUE, dpi=300, out.width=700, prompt=FALSE, comment='##', results='markup', eval=FALSE)
# See yihui.name/knitr/options for more Knitr options.
```

dbcreator FAQ
========================================================

### * How do I install databases for multiple organism?

Simply re-run the `dbcreator` modules and designate a different organism code with the **-g** argument.

### * Can I run the `dbcreator` modules on existing database?

Yes, the `dbcreator` modules skip GFs that have already been installed.

### * The `dbcreator` modules take a long time to run. Can I terminate them?

Yes, and you can restart them later. The `dbcreator` modules flags partially completed GFs with a '.temp' extension. These GFs are not visible to the `server` module, and will be installed correctly upon the next run.

### * Can I download individual GFs?

Individual GFs can be installed by giving the name to the **-f** parameter (i.e `-f knownGene`).

### * Can I simply download all genome annotation data and let the `dbcreator*` modules work with it?

In fact, this is the recommended way. `rsync` can be used to mirror the USCS data files. Simply create `[dir]/downloads/` folder and execute the following command within it:

```
rsync -avzP rsync://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/* .
```
Remember that `rsync` is not infallible. To automatically restart broken transfers, check GenomeRunner' [source code](https://github.com/mdozmorov/genome_runner/tree/master/commandline) for `autorsync.sh` script in the `commandline` folder.