# GenomeRunner

##### Author: Mikhail Dozmorov [mikhail at dozmorov dot com](mailto:mikhail@dozmorov.com), Lukas Cara, Cory Giles
##### Website: [www.genomerunner.org](http://www.genomerunner.org)  
##### Repository: [github.com//mdozmorov/genome_runner](https://github.com/mdozmorov/genome_runner)  

[GenomeRunner Web](http://www.genomerunner.org) is a tool for functional interpretation of sets of single nucleotide polymorphisms (SNPs) by considering their co-localization with functional/regulatory genome annotation data (epigenomic elements, see [definitions](misc/definitions.md)). It is particularly useful for interpretation of functional roles of rare variants and SNPs in non-protein coding regions. An example of GenomeRunner's results can be found in the analysis of Sjogren's syndrome GWAS ([Nature Genetics](http://www.nature.com/ng/journal/v45/n11/full/ng.2792.html)), where it identified RFX5 transcription factor binding site as the most statistically significantly co-localized with the disease-associated SNPs, affecting gene expression changes.

GenomeRunner Web calculates [enrichment p-values](statistics/enrichment.md) (Chi-squared test) by evaluating whether a set of SNPs co-localizes with regulatory elements more often that could happen by chance. For three or more sets of SNPs, GenomeRunner Web also implements novel idea of [epigenomic similarity](statistics/similarity.md) analysis by correlating SNP set-specific epigenomic enrichment profiles. Downloadable results are visualized as interactive heatmaps and tables.

This documentation describes inner workings of GenomeRunner Web interface and command line version, explains the statistics, conventions and terms, and provides the instructions for local installation of GenomeRunner on Linux-based systems.